name: Linting Pipeline

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependências de lint
        run: |
          pip install flake8 black

      # Removi o bloqueio do Black. Agora ele só vai checar erros graves de sintaxe.

      - name: Rodar Flake8 (Apenas Erros Graves)
        # O segredo aqui: usamos wildcard (*) para achar a venv onde ela estiver
        # E selecionamos apenas erros de sintaxe (E9, F63, etc)
        run: flake8 . --count --exclude=*.venv*,*env*,*virtual*,*node_modules* --select=E9,F63,F7,F82 --show-source --statistics