name: Linting Pipeline

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependências de lint
        run: |
          pip install flake8 black

      - name: Rodar Black (Verificação de Formatação)
        # O black vai checar se o código está bonito
        run: black --check .

      - name: Rodar Flake8 (Verificação de Erros)
        # CORREÇÃO AQUI: Adicionei --exclude para ignorar a pasta .venv e venv
        run: flake8 . --count --exclude=.venv,venv,env --select=E9,F63,F7,F82 --show-source --statistics